import Navbar from "@/components/Navbar";
import "./globals.css";

export const metadata = {
  title: "SkySuite",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="geistSans geistMono antialiased">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
